services:
  - type: web
    name: gyanmarg-library
    env: java
    plan: free
    region: oregon
    buildCommand: ./mvnw -DskipTests package
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
    autoDeploy: true