services:
  - type: web
    name: gyanmarg-library
    env: java
    plan: free
    region: oregon
    buildCommand: mvn -DskipTests package
    startCommand: java -Dserver.port=$PORT -jar target/gyan-marg-library-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m
    autoDeploy: true
